cassandra_migration_version: main
devops_release_branch: release-8.0.0

provisioningAnnotations: &provisioningAnnotations
  "helm.sh/hook-weight": "-4"

certregistry:
  enabled: true
  opa_enabled: true
lern:
  enabled: true
  opa_enabled: true
registry:
  enabled: true
  opa_enabled: false

migration:
  yugabyte:
    waitTime: 120
  postgresql:
    waitTime: 120
  opensearch:
    waitTime: 120

postgres_migration_image: sunbirded.azurecr.io/postgresql:11.14.0

job_cleaner_kubectl_image:
  registry: "sunbirded.azurecr.io"
  repository: "kubectl"
  tag: "1.28.4"

job_wait_image:
  registry: "docker.io"
  repository: "busybox"
  tag: "latest"

opensearch_migration_image:
  registry: "docker.io"
  repository: "curlimages/curl"
  tag: "latest"

kafka: &kafka
  enabled: true
  fullnameOverride: "kafka"
  clientProtocol: PLAINTEXT
  host: "kafka"
  port: 9092
  image:
    registry: sunbirded.azurecr.io
    repository: kafka
    tag: 3.3.1-debian-11-r25
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  persistence:
    size: 25Gi
  listeners:
    client:
      protocol: PLAINTEXT
  controller:
      protocol: PLAINTEXT
  interbroker:
      protocol: PLAINTEXT
  external:
      protocol: PLAINTEXT
  sasl:
    enabledMechanisms: ""
    interBrokerMechanism: ""
    controllerMechanism: ""
  tls:
    autoGenerated:
      enabled: false
    existingSecret: ""
  provisioning:
    annotations: *provisioningAnnotations
    replicationFactor: 1
    numPartitions: 1
    parallel: 1
    topics:
    - name: "{{ .Values.global.env }}.delete.user"
      partitions: 1
      replicationFactor: 1
    - name: "{{ .Values.global.env }}.issue.certificate.request"
      partitions: 1
      replicationFactor: 1
    - name: "{{ .Values.global.env }}.generate.certificate.request"
      partitions: 1
      replicationFactor: 1
    - name: "{{ .Values.global.env }}.issue.certificate.failed"
      partitions: 1
      replicationFactor: 1
    - name: "{{ .Values.global.env }}.generate.certificate.failed"
      partitions: 1
      replicationFactor: 1
    - name: "{{ .Values.global.env }}.telemetry.raw"
      partitions: 1
      replicationFactor: 1
    - name: "{{ .Values.global.env }}.lms.notification"
      partitions: 1
      replicationFactor: 1

redis: &redis
  enabled: true
  fullnameOverride: "redis"
  auth:
    enabled: false
  host: "redis-master"
  port: 6379
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  replica:
    replicaCount: 0
  master:
    persistence:
      size: 25Gi

yugabyte: &yugabyte
  enabled: true
  nameOverride: "yugabyte"
  fullnameOverride: "yugabyte"
  host: "yb-tserver-service" 
  port: 9042
  postgresql_port: 5433
  databases:
    - name: "keycloak"
    - name: "quartz"
    - name: "enc-keys"
    - name: "registry"
    - name: "sunbird"
  image:
    registry: yugabytedb
    repository: yugabyte
    tag: 2025.2.0.0-b131 
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  provisioning:
    annotations: *provisioningAnnotations  
  # Force single replica for Yugabyte masters and tservers (override subchart defaults)
  replicas:
    master: 3
    tserver: 3
  username: yugabyte  
  password: yugabyte

yugabytecql:
  image:
    repository: "ghcr.io/sunbird-spark/sunbird-yugabyte-migrations"
    tag: "develop_499032f"

opensearch: &opensearch
  enabled: true
  fullnameOverride: "opensearch"
  host: "opensearch-cluster-master"
  port: 9200
  singleNode: true
  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: ""
  config:
    opensearch.yml: |
      plugins.security.disabled: true
      search.insights.top_queries.latency.enabled: false
      search.insights.top_queries.cpu.enabled: false
      search.insights.top_queries.memory.enabled: false
  commonAnnotations:
    "helm.sh/hook-weight": "-5"
  provisioning:
    annotations: *provisioningAnnotations

keycloak:
  enabled: true
keycloak-kids-keys:
  enabled: true

flink:
  enabled: true

adminutil:
  enabled: true

cert:
  enabled: true

certificateapi:
  enabled: true

certificatesign:
  enabled: true

global:
  opensearch: *opensearch
  kafka: *kafka
  keycloak_key_configmap: keycloak-key
  keycloak_kid_keys_configmap: keycloak-kids-keys
  kong_desktop_device_consumer_names_for_opa: '["portal", "desktop"]'
  provisioningAnnotations: *provisioningAnnotations
  redis: *redis
  yugabyte: *yugabyte
