apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- .Values.provisioningAnnotations | toYaml | nindent 4 }}
spec:
  completions: 1  # Ensure the job runs successfully only once
  parallelism: 1  # Run only one pod at a time
  backoffLimit: 30
  ttlSecondsAfterFinished: 100  # Auto-cleanup job after completion
  template:
    metadata:
      labels:
        kong-admin-client: "true"
    spec:
      initContainers:
      - name: wait-for-kong
        image: busybox
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        # Wait for Kong admin endpoint to be reachable (port 8001) before seeding APIs
        args:
        - |
          timeout 600 sh -c '
            until nc -z {{ .Values.kong_admin_url }} {{ .Values.kong_admin_port }}; do
              echo "waiting for kong admin...";
              sleep 10;
            done;
            # Extra check: wait for /status to return 200
            until wget -qO- http://{{ .Values.kong_admin_url }}:{{ .Values.kong_admin_port }}/status >/dev/null 2>&1; do
              echo "waiting for kong /status ...";
              sleep 5;
            done'

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.images.kong_api_scripts.registry }}/{{ .Values.global.images.kong_api_scripts.repository }}:{{ .Values.global.images.kong_api_scripts.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /bin/sh
          - -c
          args:
            - python /kong_yaml_to_json.py && python /kong_apis.py /tmp/kong-apis.json --kong-admin-api-url=http://{{ .Values.kong_admin_url }}:{{ .Values.kong_admin_port }} --managed-by={{ .Values.managed_by }}
          volumeMounts:
          {{- if .Values.configmap.enabled }}
          - name: config
            mountPath: {{ .Values.configmap.mountPath }}
          {{- end }}
      volumes:
      {{- if .Values.configmap.enabled }}
      - name: config
        configMap:
          name: {{ include "common.names.fullname" . }}
      {{- end }}
      restartPolicy: Never