---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- .Values.provisioningAnnotations | toYaml | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        kong-admin-client: "true"
    spec:
      initContainers:
      - name: wait-for-kong
        image: busybox
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.waitForKongResources | nindent 10 }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          timeout 600 sh -c '
            until nc -z kong 8001; do
              echo "waiting for kong admin...";
              sleep 10;
            done;
            # Extra check: wait for /status to return 200
            until wget -qO- http://kong:8001/status >/dev/null 2>&1; do
              echo "waiting for kong /status ...";
              sleep 5;
            done'
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
          - /bin/sh
          - -c
          args:
            - python /kong_yaml_to_json.py && python /kong_consumers.py /tmp/kong-consumers.json --kong-admin-api-url=http://{{    .Values.kong_admin_url }}:{{ .Values.kong_admin_port }} --managed-by={{ .Values.managed_by | default "core" }}
          volumeMounts:
          {{- if .Values.configmap.enabled }}
          - name: config
            mountPath: {{ .Values.configmap.mountPath }}
          {{- end }}
      volumes:
      {{- if .Values.configmap.enabled }}
      - name: config
        secret:
          secretName: {{ include "common.names.fullname" . }}
      {{- end }}
      restartPolicy: Never
  backoffLimit: 30
