SUNBIRD_SESSION_SECRET: "{{ .Values.global.random_string }}"
GOOGLE_OAUTH_CLIENT_SECRET: "{{.Values.global.sunbird_google_oauth_clientSecret | default ""}}"
KONG_ANONYMOUS_FALLBACK_TOKEN: "{{.Values.global.sunbird_anonymous_default_token}}"
KONG_ANONYMOUS_DEVICE_REGISTER_TOKEN: "{{.Values.global.sunbird_anonymous_register_token}}"
KONG_LOGGEDIN_FALLBACK_TOKEN: "{{.Values.global.sunbird_logged_default_token}}"
KONG_LOGGEDIN_DEVICE_REGISTER_TOKEN: "{{.Values.global.sunbird_loggedin_register_token}}"
GOOGLE_RECAPTCHA_SECRET: "{{.Values.global.google_captcha_private_key | default ""}}"
KEYCLOAK_GOOGLE_CLIENT_SECRET: "{{ .Values.google_auth_client_secret }}{{ .Values.global.random_string }}"
KEYCLOAK_ANDROID_CLIENT_SECRET: "{{ .Values.android_client_secret }}{{ .Values.global.random_string }}"
KEYCLOAK_GOOGLE_ANDROID_CLIENT_SECRET: "{{.Values.sunbird_google_android_keycloak_secret}}{{.Values.global.random_string}}"
