name: Docker Build and Push

on:
  push:
    tags:
      - 'spark-v*'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - keycloak-21.1.2
          - keycloak-postgres-query
          - kong-api-scripts
          - sunbird-yugabyte-migrations
          - janusgraph
          - yugabyte-backup
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repository owner and generate tag
        id: prep
        run: |
          echo "OWNER_LOWERCASE=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
          # Format: spark-v<tag>_<short-sha> e.g. spark-v1.0.2_abc1234
          GIT_TAG="${GITHUB_REF_NAME}"
          RAW_TAG="${GIT_TAG}_${GITHUB_SHA::7}"
          echo "IMAGE_TAG=$(echo $RAW_TAG | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./scripts/${{ matrix.directory }}
          file: ./scripts/${{ matrix.directory }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.prep.outputs.OWNER_LOWERCASE }}/${{ matrix.directory }}:${{ steps.prep.outputs.IMAGE_TAG }}
            ghcr.io/${{ steps.prep.outputs.OWNER_LOWERCASE }}/${{ matrix.directory }}:latest
